### ISSUE TITLE
Remarable don't compatible with Rspec 2.0.0.beta.19

### ISSUE THREAD

**Issue by petRUShka** [remarkable-rb/remarkable#16]
<pre><code>
Bundler could not find compatible versions for gem "rspec":
  In Gemfile:
    rspec-rails (= 2.0.0.beta.19) depends on
      rspec (= 2.0.0.beta.19)

    remarkable_activemodel (= 4.0.0.alpha4) depends on
      rspec (2.0.0.beta.16)
</code></pre>

**Comment by hosh** [comment]
That's weird, I didn't run into that when I used beta.19 and Rails 3RC

**Comment by hosh** [comment]
This is from my Gemfile.lock:

```
remarkable (4.0.0.alpha4)
  rspec (>= 2.0.0.alpha11)
remarkable_activemodel (4.0.0.alpha4)
  remarkable (~> 4.0.0.alpha4)
  rspec (>= 2.0.0.alpha11)
remarkable_activerecord (4.0.0.alpha4)
  remarkable (~> 4.0.0.alpha4)
  remarkable_activemodel (~> 4.0.0.alpha4)
  rspec (>= 2.0.0.alpha11)
```

**Comment by petRUShka** [comment]
It's issue of new (1.0.0.rc) bundler, sorry
