### ISSUE TITLE
Remarkable has no gemspec. Cannot install from repo.

### ISSUE THREAD

**Issue by HashNuke** [remarkable-rb/remarkable#34]
The remarkable repo has no gemspec file, making it tough to add the repo as the gem source directly into the Gemfile (correct me if I'm wrong pleaes).

I see that the details that go into the gemspec are already in the Rakefile, but it would be better to have a seperate gemspec. Would be useful for those who are using the latest and maybe-greatest code of the repo.

**Comment by hosh** [comment]
You need to do a rake gemspec before running bundle. (I ran into this one earlier today). So the real issue is whether to include gemspec in the repo or not.

For now, I'm not. We can reopen this issue after we get it working in Rails 3.1.

**Comment by HashNuke** [comment]
@hosh oh, so that means we cannot use the git source in the Gemfile?

**Comment by hosh** [comment]
@hashnuke You can. I just did yesterday. Here's how you do it:

(1) Setup the Gemfile (you've already done this).

(2) _Before_ typing "bundle", type

( cd vendor/gems/remarkable; rake gemspec )

... If that does not work, you probably do not have Jeweler installed. 

(3) bundle

Let me know if you have problems with this approach.

By the way, why are you installing from source? The alpha4 gem is available and works all the way up to 3.0.10.

**Comment by HashNuke** [comment]
@hosh thanks I'll try it out in a few minutes.

Actually I was having problems with have_scope and noticed that there's a fix in the Rails 3.1 branch, so was looking to use it.

**Comment by hosh** [comment]
Gotcha. Yeah, the Rails 3.1 branch is not ready for prime time. Up until now, I've used respond_to matcher instead of have_scope matchers.
